# indent
set-option global tabstop     4
set-option global indentwidth 0

# line numbers
add-highlighter global/ number-lines -relative -hlcursor -separator '  '

# wrap
add-highlighter global/ wrap -indent

# show whitespaces
add-highlighter global/ show-whitespaces -spc '' -lf '' -tab '>'

# autopairs
map global insert { {}<left>
map global insert ( ()<left>
map global insert [ []<left>
map global insert \' \''<left>
map global insert \" \""<left>

# insert mode movement
map global insert <c-h> <left>
map global insert <c-j> <down>
map global insert <c-k> <up>
map global insert <c-l> <right>

# clipboard
map global user p -docstring 'paste from clipboard' '!wl-paste -n<ret>'
map global user y -docstring 'copy to clipboard' '<a-|>wl-copy<ret>'
map global user d -docstring 'cut to clipboard' '<a-|>wl-copy<ret>d'

# editorconfig
hook global WinCreate ^[^*]+$ %{editorconfig-load}

# initial message
set-option global startup_info_version 99999999
