#!/bin/sh

OUT=$(pactl list short sinks | grep -w 'RUNNING' | head -c 1)

if [ $OUT -eq 1 ]; then
	pacmd set-default-sink 0
elif [ $OUT -eq 0 ]; then
	pacmd set-default-sink 1
fi

echo "Audio output modified"
