# HOME
XDG_CONFIG_HOME=$HOME/.config
XDG_CACHE_HOME=$HOME/.cache
XDG_DATA_HOME=$HOME/.local/share
XDG_STATE_HOME=$HOME/.local/state

CARGO_HOME=$XDG_CONFIG_DIR/cargo

# HIST
HISTFILE=${ZDOTDIR}/.zsh_history
HISTSIZE=1000
SAVEHIST=1000
LESSHISTFILE=-
